// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NAuth.Infra.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NAuth.Infra.Migrations
{
    [DbContext(typeof(NAuthContext))]
    partial class NAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("role_id_seq");

            modelBuilder.HasSequence("user_addresses_id_seq");

            modelBuilder.HasSequence("user_documents_id_seq");

            modelBuilder.HasSequence("user_id_seq");

            modelBuilder.HasSequence("user_phones_id_seq");

            modelBuilder.Entity("NAuth.Infra.Context.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("nextval('role_id_seq'::regclass)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.HasKey("RoleId")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NAuth.Infra.Context.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("nextval('user_id_seq'::regclass)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("email");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash");

                    b.Property<string>("IdDocument")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("id_document");

                    b.Property<string>("Image")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("image");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_admin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("PixKey")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("pix_key");

                    b.Property<string>("RecoveryHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("recovery_hash");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<string>("StripeId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("stripe_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserAddress", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("address_id")
                        .HasDefaultValueSql("nextval('user_addresses_id_seq'::regclass)");

                    b.Property<string>("Address")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<string>("Complement")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("complement");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("neighborhood");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("state");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("zip_code");

                    b.HasKey("AddressId")
                        .HasName("pk_user_addresses");

                    b.HasIndex("UserId");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id")
                        .HasDefaultValueSql("nextval('user_documents_id_seq'::regclass)");

                    b.Property<string>("Base64")
                        .HasColumnType("text")
                        .HasColumnName("base64");

                    b.Property<int>("DocumentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("document_type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("DocumentId")
                        .HasName("user_documents_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_documents", (string)null);
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserPhone", b =>
                {
                    b.Property<long>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("phone_id")
                        .HasDefaultValueSql("nextval('user_phones_id_seq'::regclass)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("PhoneId")
                        .HasName("user_phones_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("user_phones", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserAddress", b =>
                {
                    b.HasOne("NAuth.Infra.Context.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserDocument", b =>
                {
                    b.HasOne("NAuth.Infra.Context.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NAuth.Infra.Context.UserPhone", b =>
                {
                    b.HasOne("NAuth.Infra.Context.User", "User")
                        .WithMany("UserPhones")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_phone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("NAuth.Infra.Context.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role");

                    b.HasOne("NAuth.Infra.Context.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_role_user");
                });

            modelBuilder.Entity("NAuth.Infra.Context.User", b =>
                {
                    b.Navigation("UserAddresses");

                    b.Navigation("UserDocuments");

                    b.Navigation("UserPhones");
                });
#pragma warning restore 612, 618
        }
    }
}
